config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :accounts do
    post "sync", on: :member
    post "import", on: :member
  end

  resources :sessions do
    post "link", on: :member
    get "callback", on: :collection
  end

  root "pages#home"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:amount, :counterparty, :reference, :description)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :counterparty, style: "display: block" %>
    <%= form.text_field :counterparty %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div class="box" id="<%= dom_id transaction %>">
  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

  <p>
    <strong>Other:</strong>
    <%= transaction.counterparty %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= transaction.description %>
  </p>

</div>

app/views/transactions/_transactions_table.html.erb
<section class="box">
  <table class="table is-striped is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-right">Account</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Payee</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% transactions.each do |transaction| %>
      <tr>
        <td class="has-text-right">
          <span class="tag is-dark" style="background-color: <%= transaction.account.color %>">
            <%= transaction.account.short_name %>
          </span>
        </td>
        <td><%= transaction.effective_at %></td>
        <% if transaction.amount.positive? %>
          <td class="has-text-success-dark"><%= transaction.amount %></td>
        <% else %>
          <td class="has-text-danger-dark"><%= transaction.amount %></td>
        <% end %>
        <td><%= transaction.counterparty %></td>
        <td><%= transaction.description %></td>
        <td>
          <%= link_to transaction_path(transaction), class: 'button is-info is-light is-small' do %>
            <i class="ri-edit-2-line"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title">Transactions</p>
  </div>
</section>

<%= render 'transactions_table', transactions: @transactions %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>