config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :accounts do
    post "sync", on: :member
    post "import", on: :member
  end

  resources :sessions do
    post "link", on: :member
    get "callback", on: :collection
  end

  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <title>Klutters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body class="has-background-light" style="min-height: 100vh">
    <nav class="navbar is-white">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Klutters", root_path, class: "navbar-item brand-text" %>
          <%= link_to "Transactions", transactions_path, class: "navbar-item" %>
          <%= link_to "Accounts", accounts_path, class: "navbar-item" %>
          <%= link_to "Sessions", sessions_path, class: "navbar-item" %>
        </div>
      </div>
    </nav>
    <main class="container">
      <% if defined?(notice) && notice.present? %>
        <div class="container>">
          <div class="notification is-primary is-light">
            <%= notice %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>