config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :accounts do
    post "sync", on: :member
    post "import", on: :member
  end

  resources :sessions do
    post "link", on: :member
    get "callback", on: :collection
  end

  root "pages#home"
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id               :bigint           not null, primary key
#  balance_cents    :integer          default(0), not null
#  balance_currency :string           default("EUR"), not null
#  color            :string           not null
#  full_name        :string           not null
#  short_name       :string           not null
#  uid              :string
#  verified         :boolean          default(FALSE), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  session_id       :bigint
#
# Indexes
#
#  index_accounts_on_session_id  (session_id)
#
class Account < ApplicationRecord
  belongs_to :session
  has_many :transactions

  delegate :active?, :valid_until, :bank, :country, to: :session

  monetize  :balance_cents

  validates :uid, presence: true
  validates :short_name, :full_name, presence:true, allow_blank: true

  def update_balance_with(balances_json)
    bal = balances_json.find { |b| b[:balance_type] == 'XPCD'} || \
          balances_json.find { |b| b[:balance_type] == 'CLBD'} || \
          balances_json.last
    self.balance = parse_money(bal[:balance_amount])
    save
  end

  def update_transactions_with(transactions_json)
    changed = 0

    transactions_json.each do |json|
      transaction = transactions.find_or_initialize_by(reference: json[:entry_reference])
      amount = parse_money(json[:transaction_amount])
      case json[:credit_debit_indicator]
      when "DBIT"
        transaction.amount = -amount
      when "CRDT"
        transaction.amount = amount
      else
        raise "Unrecognised credit_debit_indicator: #{json[:credit_debit_indicator]}"
      end
      transaction.status = json[:status]
      transaction.effective_at = json[:booking_date]
      transaction.description = json[:remittance_information].join("\n")

      if transaction.changed?
        changed += 1
        transaction.save
      end
    end

    changed
  end

  private

  def parse_money(hash)
    (hash[:amount] + hash[:currency]).to_money
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy sync import]
  before_action :set_tilisy, only: %i[sync]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to account_url(@account), notice: "Account was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    if @account.update(account_params)
      redirect_to account_url(@account), notice: "Account was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    redirect_to accounts_url, notice: "Account was successfully destroyed."
  end

  def sync
    @tilisy.fetch_balance(@account)
    @tilisy.fetch_transactions(@account)

    redirect_back_or_to account_url(@account)
  end

  def import
    importer = Importer::Csv.new(@account)
    csv_file = params[:account][:csv].tempfile
    transactions = importer.import(csv_file)
    transactions.each(&:save!)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:full_name, :short_name, :color, :bank, :country)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Name:</strong>
    <%= account.full_name %>
  </p>

  <p>
    <strong>Bank:</strong>
    <%= account.bank %>
  </p>

  <p>
    <strong>Uid:</strong>
    <%= account.uid %>
  </p>

  <p>
    <strong>Valid until:</strong>
    <%= account.valid_until %>
  </p>

</div>

app/views/accounts/_account_card.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <% if account.full_name.blank? %>
          <p class="title is-4 has-text-grey">Unnamed account</p>
        <% else %>
          <p class="title is-4"><%= account.full_name %></p>
        <% end %>
        <p class="subtitle is-6"><%= account.bank %></p>
      </div>
      <div class="media-right">
        <%= form_with model: account, url: import_account_path(account), method: :post, html: { id: "csv_import_form" } do |f| %>
          <div class="file">
            <label class="file-label">
              <%= f.file_field(:csv, accept: 'text/csv', class: 'file-input') %>
              <script>
                window.addEventListener("load", function() {
                  document.getElementById("account_csv").addEventListener("change", function() {
                    document.getElementById("csv_import_form").submit();
                  });
                });
              </script>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="ri-upload-cloud-2-line"></i>
                </span>
                <span class="file-label">
                  Import CSV
                </span>
              </span>
            </label>
          </div>
        <% end %>
      </div>
    </div>

    <div class="content">
      <div class="level">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Balance</p>
            <p class="title"><%= account.balance.format %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Transactions</p>
            <p class="title"><%= account.transactions.count %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Status</p>
            <% if account.active? %>
              <p class="title has-text-success">ONLINE</p>
            <% else %>
              <p class="title has-text-danger">OFFLINE</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Transactions", account_path(account), class: 'card-footer-item' %>
    <%= link_to "Edit", edit_account_path(account), class: 'card-footer-item' %>
    <%= button_to "Relink", link_session_path(account.session), form_class: "card-footer-item" %>
    <%= button_to "Sync", sync_account_path(account), form_class: "card-footer-item" %>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div class="notification is-danger">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name, class: "label" %>
    <div class="control">
      <%= form.text_field :full_name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :short_name, class: "label" %>
    <div class="control">
      <%= form.text_field :short_name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :color, class: "label" %>
    <div class="control">
      <%= form.text_field :color, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="section">
  <nav class="breadcrumb">
    <ul>
      <li>
        <%= link_to "Accounts", accounts_path %>
      </li>
      <li>
        <%= link_to @account.full_name, account_path(@account) %>
      </li>
      <li>Edit</li>
    </ul>
  </nav>
</div>

<%= render "form", account: @account %>

app/views/accounts/index.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title">Accounts</p>
  </div>
</section>

<div class="columns">
  <% @accounts.each do |account| %>
    <div class="column">
      <%= render 'account_card', account: account %>
    </div>
  <% end %>
</div>

<%= link_to new_session_path, class: "button" do %>
  <i class="ri-add-circle-fill"></i>&nbsp;Add accounts
<% end %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>